### ISSUE TITLE
Unexpected flow completion for not focused image

### ISSUE THREAD

**Issue by iuriimoz** [onfido/onfido-ios-sdk#168]
### What was the expected behaviour?
1. Put your iPhone on table and start Onfido flow with passport document step
2. Immediately take blank photo
3. UI should display "Blurry photo detected" message

### What happened instead?

Onfido flow completed with error: Domain=AVFoundationErrorDomain, Code=-11800

### Version info:

- Onfido SDK (Debug/Release): 18.2.0
- iOS: 13.3.1
- Xcode: 11.3.1
- Device/Simulator: iPhone 6s
- Device/Simulator language: English

### Integration configuration:
```
let onfidoConfig = OnfidoConfig.builder()
    .withSDKToken(sdkToken)
    .withDocumentStep(ofType: DocumentType.passport(config: nil))
    .withFaceStep(ofVariant: .video(withConfiguration: nil))
    .withCustomLocalization()
    .withAppearance(appearance)
    .build()

let onfidoFlow = OnfidoFlow(withConfiguration: onfidoConfig)
    .with(responseHandler: { response in
        OnfidoAnalytics.handleResponse(response)
        responseHandler(response)
    }, dismissFlowOnCompletion: dismissFlowOnCompletion)
    .with { event in
        OnfidoAnalytics.handleEvent(event)
}
```
### Steps to reproduce:

1. Put your iPhone on table and start Onfido flow with passport document step
2. Immediately take blank photo
3. Onfido flow completes with error.

![IMG_0924](https://user-images.githubusercontent.com/1536479/87474993-a8bc6100-c62c-11ea-9691-b664ed716721.gif)

**Comment by keremgund** [comment]
Hi @iuriimoz ,
I was able to reproduce the issue and started to work on the fix. 
I will give an update once we released version which resolves the problem. 

Sorry for the inconvenience and thanks for reporting the issue,
Kerem

**Comment by anuragajwani** [comment]
Hi @iuriimoz 

The fix for this problem is now on version 18.3.1

**Comment by anuragajwani** [comment]
@iuriimoz please let us know if this has fixed your problem.

Thanks,
Anurag

**Comment by keremgund** [comment]
Closing the issue due to lack of response. Please open new one if your problem persists.

**Comment by wisyaa** [comment]
My boost app when i do blur and let my picture become blacks it still dont want to recover yet , so how ?
