### ISSUE TITLE
NSInternalInconsistencyException:  __hidden#25724_ line 72 SelfieIntroViewController.viewDidLoad() 

### ISSUE THREAD

**Issue by bart-kneepkens** [onfido/onfido-ios-sdk#239]
### What was the expected behaviour?

We expect users to be able to use Onfido without crashing the application

### What happened instead?

The application crashes after user uploads something, leaving a stacktrace that suggests it's coming from Onfido:

`Not possible to remove variable: 462: <unknown var (bug!) with engine as delegate:0x2821453c0>{id: 6073} colIndex:11 from engine <NSISEngine: 0x117053a10>{ delegate:0x125223ce0 EngineVars: 0: objective{id: 6023} rowIndex:0 1: Onfido.OnfidoLabel:0x1252538c0.Width{id: 5845} rowIndex:66 2: 0x281ea42a0.posErrorMarker{id: 5841} colIndex:16 3: 0x281ea42a0.negError{id: 5842} rowIndex:26 4: Onfido.OnfidoLabel:0x1252538c0.Height{id: 5846} colIndex:1073741932 5: 0x281ea6e20.posErrorMarker{id: 5843} colIndex:1073741825 6: 0x281ea6e20.negError{id: 5844} rowIndex:1073741824 7: Onfido.OnfidoLabel:0x125253d00.Width{id: 5851} colIndex:125 8: 0x281ea4480.posErrorMarker{id: 5847} colIndex:17 9: 0x281ea4480.negError{id: 5848} rowIndex:1 10: Onfido.OnfidoLabel:0x125253d00.Height{id: 5852} rowIndex:1073741925 11: 0x281ea6e80.posErrorMarker{id: 5849} colIndex:1073741827 12: 0x281ea6e80.negError{id: 5850} rowIndex:79 13: 0x2818ac230:UISV-ambiguity-suppression.posErrorMarker{id: 5867} rowIndex:1073741826 14: 0x2818ac230:UISV-ambiguity-suppression.negError{id: 5868} colIndex:1073741830 15: UIStackView:0x125253b70.minX{id: 5854} rowIndex:8 16: Onfido.OnfidoLabel:0x125253d00.minX{id: 5855} rowIndex:3 17: 0x2818aeb20:UISV-canvas-connection.marker{id: 5853} colIndex:6 18: UIStackView:0x125253b70.Width{id: 5857} colIndex:126 19: 0x2818af250:UISV-canvas-connection.marker{id: 5856} colIndex:8 20: 0x2818af660:UISV-text-width-disambiguation.posErrorMarker{id: 5858} rowIndex:5 21: 0x2818af660:UISV-text-width-disambiguation.negError{id: 5859} colIndex:10 22: UIStackView:0x125253b70.minY{id: 5861} rowIndex:1073741831 23: Onfido.OnfidoLabel:0x125253d00.minY{id: 5862} rowIndex:1073741827 24: 0x2818ae620:UISV-canvas-connection.marker{id: 5860} colIndex:1073741831 25: UIStackView:0x125253b70.Height{id: 5864} colIndex:1073741945 26: 0x2818af750:UISV-canvas-connection.slackMarker{id: 5863} colIndex:1073741848 27: 0x2818af4d0:UISV-canvas-fit.posErrorMarker{id: 5865} rowIndex:1073741829 28`

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x19540a754 __exceptionPreprocess
1  libobjc.A.dylib                0x1a9ed17a8 objc_exception_throw
2  CoreFoundation                 0x19530c3f8 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x196733a6c -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:]
4  CoreAutoLayout                 0x1aa15e270 _engineVar_rawRemove
5  CoreAutoLayout                 0x1aa15f440 -[NSISEngine removeConstraintWithMarker:]
6  CoreAutoLayout                 0x1aa176658 -[NSLayoutConstraint _removeFromEngine:]
7  UIKitCore                      0x19823bdf0 -[UIView(UIConstraintBasedLayout) _layoutEngine_willRemoveLayoutConstraint:]
8  UIKitCore                      0x19823ca8c -[UIView(UIConstraintBasedLayout) nsli_removeConstraint:]
9  CoreAutoLayout                 0x1aa1779d4 __55+[NSLayoutConstraint _addOrRemoveConstraints:activate:]_block_invoke
10 CoreAutoLayout                 0x1aa15cae4 -[NSISEngine withBehaviors:performModifications:]
11 CoreAutoLayout                 0x1aa17789c +[NSLayoutConstraint _addOrRemoveConstraints:activate:]
12 UIKitCore                      0x198248c3c -[UIView(AdditionalLayoutSupport) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:]
13 UIKitCore                      0x198249d64 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:]
14 UIKitCore                      0x19824ae4c -[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:]
15 UIKitCore                      0x198325bb0 -[UIView(Hierarchy) layoutBelowIfNeeded]
16 Onfido                         0x103813f90 SelfieIntroViewController.viewDidLoad() + 72 (__hidden#25724_:72)
17 Onfido                         0x103813fcc _hidden#25693_ (__hidden#3081_)
18 UIKitCore                      0x1976cb078 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]
19 UIKitCore                      0x1976cf8a0 -[UIViewController loadViewIfRequired]
20 UIKitCore                      0x1976cfc64 -[UIViewController view]
21 UIKitCore                      0x1975fa7fc -[UINavigationController _startCustomTransition:]
22 UIKitCore                      0x19760f8e4 -[UINavigationController _startDeferredTransitionIfNeeded:]
23 UIKitCore                      0x197610d74 -[UINavigationController __viewWillLayoutSubviews]
24 UIKitCore                      0x1975f2944 -[UILayoutContainerView layoutSubviews]
25 UIKitCore                      0x198339a0c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
26 QuartzCore                     0x1987c0670 -[CALayer layoutSublayers]
27 QuartzCore                     0x1987c0b54 CA::Layer::layout_if_needed(CA::Transaction*)
28 QuartzCore                     0x1987d578c CA::Layer::layout_and_display_if_needed(CA::Transaction*)
29 QuartzCore                     0x1987175e4 CA::Context::commit_transaction(CA::Transaction*, double, double*)
30 QuartzCore                     0x1987437f4 CA::Transaction::commit()
31 QuartzCore                     0x198744b20 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
32 CoreFoundation                 0x1953835e0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
33 CoreFoundation                 0x19537d704 __CFRunLoopDoObservers
34 CoreFoundation                 0x19537dcb0 __CFRunLoopRun
35 CoreFoundation                 0x19537d360 CFRunLoopRunSpecific
36 GraphicsServices               0x1ac9bb734 GSEventRunModal
37 UIKitCore                      0x197df8584 -[UIApplication _run]
38 UIKitCore                      0x197dfddf4 UIApplicationMain
39 XXXXX                          0x102619164 main + 15 (main.swift:15)
40 libdyld.dylib                  0x195039cf8 start
```

### Version info:
- Onfido SDK (Release): 21.4.0 
- iOS: 14.6.0

### Integration configuration:

I've redacted some parts (`###`).

```
let appearance = Onfido.Appearance(
                primaryColor: ####,
                primaryTitleColor: ###,
                primaryBackgroundPressedColor: ###,
                secondaryBackgroundPressedColor: ###,
                fontRegular: ###,
                fontBold: ###,
                supportDarkMode: false)

let config = try OnfidoConfig.builder()
                .withSDKToken(token)
                .withWelcomeStep()
                .withDocumentStep(ofType: .drivingLicence(config: DrivingLicenceConfiguration(country: countryCodeISO3166)))
                .withFaceStep(ofVariant: .photo(withConfiguration: nil))
                .withCustomLocalization()
                .withAppearance(appearance)
                .build()

let onfidoFlow = OnfidoFlow(withConfiguration: config)
                .with(eventHandler:  { (event: Event) -> () in
                         // Analytics
                })
                .with { response in  ### }
            
let onfidoViewController = try onfidoFlow.run()
```

            

### Steps to reproduce:
We've been unable to reproduce this issue manually - we only see it in our Crashlytics

**Comment by buh** [comment]
up!

**Comment by anuragajwani** [comment]
Hi @bart-kneepkens,

Is this happening on a specific device or devices? I am unable to reproduce the issue either.

**Comment by bart-kneepkens** [comment]
Hi @anuragajwani, thanks for your response, we're seeing this specifically on iPhone 11 and iPhone XR (6.06").

**Comment by buh** [comment]
up!

**Comment by buh** [comment]
@anuragajwani hey! Are you guys working on it or not? It's been a month now.

**Comment by buh** [comment]
Hey guys!
This is our #1 crash ☹️
Is there anything you can do? Or should we find another service?

**Comment by anuragajwani** [comment]
hey @buh,

we are unable to reproduce it. In these cases we try to adopt defensive coding strategies around the crash and see if on the next release we can surface a more meaningful error message.

Sorry about the inconvenience,
Anurag

**Comment by anuragajwani** [comment]
@buh, @bart-kneepkens,

do any of you track the user journey using user analytics sdk feature?

https://github.com/onfido/onfido-ios-sdk#user-analytics

If you do is it possible to share the user journey which led to some of these crashes please?

**Comment by buh** [comment]
Can you share `viewDidLoad` method?

**Comment by buh** [comment]
```
1 OnfidoDocumentUpload
2 OnfidoDocumentCaptureConfirmationBack
3 OnfidoDocumentCaptureBack
4 OnfidoDocumentUpload
5 OnfidoDocumentCaptureConfirmationFront
6 OnfidoDocumentCaptureFront
7 OnfidoWelcome
8 LicenseVerificationStarted
```

**Comment by buh** [comment]
```
Not possible to remove variable: 
462: <unknown var (bug!) with engine as delegate:0x28171c200>{id: 5977} colIndex:6 from engine <NSISEngine: 0x11320ef30>{ delegate:0x108b482e0 EngineVars: 
0: objective{id: 5927} rowIndex:0 
1: Onfido.OnfidoLabel:0x11320bcb0.Width{id: 5749} rowIndex:66 
2: 0x282631aa0.posErrorMarker{id: 5745} colIndex:16 
3: 0x282631aa0.negError{id: 5746} rowIndex:26 
4: Onfido.OnfidoLabel:0x11320bcb0.Height{id: 5750} colIndex:1073741932 
5: 0x282631c20.posErrorMarker{id: 5747} colIndex:1073741825 
6: 0x282631c20.negError{id: 5748} rowIndex:1073741824 
7: Onfido.OnfidoLabel:0x11320c0f0.Width{id: 5755} colIndex:125 
8: 0x282631ce0.posErrorMarker{id: 5751} colIndex:17 
9: 0x282631ce0.negError{id: 5752} rowIndex:1 
10: Onfido.OnfidoLabel:0x11320c0f0.Height{id: 5756} rowIndex:1073741925 
11: 0x282631e00.posErrorMarker{id: 5753} colIndex:1073741827 
12: 0x282631e00.negError{id: 5754} rowIndex:79 
13: 0x28211fca0:UISV-ambiguity-suppression.posErrorMarker{id: 5771} rowIndex:1073741826 
14: 0x28211fca0:UISV-ambiguity-suppression.negError{id: 5772} colIndex:1073741830 
15: UIStackView:0x11320bf60.minX{id: 5758} rowIndex:8 
16: Onfido.OnfidoLabel:0x11320c0f0.minX{id: 5759} rowIndex:3 
18: UIStackView:0x11320bf60.Width{id: 5761} colIndex:126 
19: 0x28211fbb0:UISV-canvas-connection.marker{id: 5760} colIndex:8 
20: 0x28211f8e0:UISV-text-width-disambiguation.posErrorMarker{id: 5762} rowIndex:5 
21: 0x28211f8e0:UISV-text-width-disambiguation.negError{id: 5763} colIndex:10 
22: UIStackView:0x11320bf60.minY{id: 5765} rowIndex:1073741831 
23: Onfido.OnfidoLabel:0x11320c0f0.minY{id: 5766} rowIndex:1073741827 
24: 0x28211f7a0:UISV-canvas-connection.marker{id: 5764} colIndex:1073741831 
25: UIStackView:0x11320bf60.Height{id: 5768} colIndex:1073741945 
26: 0x28211f390:UISV-canvas-connection.slackMarker{id: 5767} colIndex:1073741848 
27: 0x28211efd0:UISV-canvas-fit.posErrorMarker{id: 5769} rowIndex:1073741829 
28: 0x28211efd0:UISV-canvas-fit.negError{id: 5770} colIndex:1073741835
```

**Comment by anuragajwani** [comment]
@buh:

```
override func viewDidLoad() {
        super.viewDidLoad()
        self.configureIntroView()
        self.configureNavigationBar()
        self.view.layoutIfNeeded()
    }
```

The crashing line is:
```
self.view.layoutIfNeeded()
```

**Comment by buh** [comment]
@anuragajwani Obviously the posted code is useless for me. Can you show how did you layout components?
Basically, we need everything related to your layout.

**Comment by anuragajwani** [comment]
@buh sorry for the late reply. Our SDK uses a lot of reusable components so getting the full code would require some time and sticking of the code. This would error prone.

Before someone gets into this on our side, how often is this happening? We haven't had a single incident in our testing (we third party testers that continuously perform exploratory testing where we incentives them to crash our SDK).

**Comment by buh** [comment]
More importantly, it happens every day

**Comment by bart-kneepkens** [comment]
Now at 986 crash events affecting 349 users. Is there anything we can do to help get a fix out the door? #246 seems related. 
We're receiving low ratings from users specifically mentioning this issue

**Comment by anuragajwani** [comment]
please note I am just scrapping all the code performed step wise in the view did load:
```
// 1. intro view

// 1.1 Loading:

// 1.2 contianer view:

let view = UIView()
view.translatesAutoresizingMaskIntoConstraints = false
self.addSubview(view)
self.headerStructureViewContainer = view

// steps summary view:

let label = OnfidoLabel()
label.translatesAutoresizingMaskIntoConstraints = false
label.text = self.viewData.stepsSummary
self.displayTextConfigurator.configureBody(label, isModalyPresented: self.deviceTypeConfig.isModal)
label.numberOfLines = 0
self.addSubview(label)
self.stepsSummaryLabel = label

// steps stack view

let stackView = UIStackView()
stackView.translatesAutoresizingMaskIntoConstraints = false
stackView.axis = .vertical
stackView.spacing = 23
self.addSubview(stackView)
self.viewData.steps
            .enumerated()
            .forEach({ (offset, step) in self.addStep(step, in: stackView, with: <REMOVED_ID>) })
self.stepsStackView = stackView

// step view

private func addStep(_ step: StepViewData, in stackView: UIStackView, with accessibilityIdentifier: String) {
        let view = StepView(
            ... <REMOVED_OTHER_DEPS>
            viewData: step)
        view.translatesAutoresizingMaskIntoConstraints = false
        view.accessibilityIdentifier = accessibilityIdentifier
        stackView.addArrangedSubview(view)
    }
    
I can share the above but again needs scrapping
```

Apart from that there are buttons at the bottom. Again needs lots of code scrapping to put up all together but I believe the problem is here given the reported bug to apple:
https://developer.apple.com/forums/thread/674689

I am sorry to see this happening but we haven't got a single crash from our testers on this.


Just one quick sanity check you are all presenting full screen presentation mode on iPhones right?
https://github.com/onfido/onfido-ios-sdk/blob/master/SampleApp/SampleApp/ViewController.swift#L56

I have seen lately some customers using page sheet presentation and we do not support page sheet.

**Comment by bart-kneepkens** [comment]
Thanks for your response @anuragajwani. Indeed, we are _not_ explicitly setting the `modalPresentationStyle` property, so it defaults to `automatic` - besides this crash, we didn't see any other issues because of this.

I'll update the `modalPresentationStyle` to be `.fullScreen` and see if the problem persists, hopefully this fixes it :)

**Comment by bart-kneepkens** [comment]
@anuragajwani Hello, we've released with explicitly setting `modalPresentatyionStyle` to `fullScreen`, but unfortunately we're seeing the very same crash occur in this version.

**Comment by buh** [comment]
Still a lot of crashes only on iPhone 11
```swift
__hidden#25724_ - Line 72
SelfieIntroViewController.viewDidLoad() + 72
```

**Comment by bas9990** [comment]
UP!

**Comment by iangmaia** [comment]
Can anyone having this issue confirm it still happens when using SDK `v23.x`?
We haven't upgraded it yet, so the crashes are still coming on `v22.x`.

**Comment by gupalov** [comment]
@iangmaia It crashes with 23.0.0 too.

**Comment by iangmaia** [comment]
I'm not sure yet if this will solve the issue, but we're gonna try `PhotoStepConfiguration(showSelfieIntroScreen: false)` in the Onfido setup, so this screen will be just skipped for now, and we'll add our own info before.

@anuragajwani I've also noticed that there are a lot of errors and constraints breaking in the console for `SelfieIntroViewController` when I was debugging the flow. This is definitely something to look into, as the crash seems to be layout related.

```
Swinject: Resolution failed. Expected registration:
	{ Service: (Event) -> (), Factory: (Resolver) -> (Event) -> () }
Available registrations:
Swinject: Resolution failed. Expected registration:
	{ Service: (Event) -> (), Factory: (Resolver) -> (Event) -> () }
Available registrations:
2021-11-09 13:31:59.084595+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002263bb0 UILabel:0x7fb2de530640.centerX == Primary Button.centerX   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x6000022600f0 H:|-(16)-[UILabel:0x7fb2de530640]   (active, names: Primary Button:0x7fb2de5304a0, '|':Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002260910 Primary Button.trailing == bottom_buttons_view.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261540 H:|-(16)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263840 H:|-(0)-[bottom_buttons_view]   (active, names: bottom_buttons_view:0x7fb2de52f520, '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x6000022639d0 bottom_buttons_view.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x60000226f7a0 '_UITemporaryLayoutWidth' Onfido.IntroView:0x7fb2d61a7270.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002263bb0 UILabel:0x7fb2de530640.centerX == Primary Button.centerX   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.085253+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000022600f0 H:|-(16)-[UILabel:0x7fb2de530640]   (active, names: Primary Button:0x7fb2de5304a0, '|':Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x6000022607d0 UILabel:0x7fb2de530640.trailing == Primary Button.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002260910 Primary Button.trailing == bottom_buttons_view.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261540 H:|-(16)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263840 H:|-(0)-[bottom_buttons_view]   (active, names: bottom_buttons_view:0x7fb2de52f520, '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x6000022639d0 bottom_buttons_view.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x60000226f7a0 '_UITemporaryLayoutWidth' Onfido.IntroView:0x7fb2d61a7270.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000022607d0 UILabel:0x7fb2de530640.trailing == Primary Button.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.086024+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002217200 H:|-(16)-[UIStackView:0x7fb2de52bee0]   (active, names: '|':Onfido.IntroBodyView:0x7fb2de543640 )>",
    "<NSLayoutConstraint:0x600002216940 UIStackView:0x7fb2de52bee0.trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active)>",
    "<NSLayoutConstraint:0x6000021cd6d0 H:|-(0)-[Onfido.IntroBodyView:0x7fb2de543640]   (active, names: '|':UIView:0x7fb2de52e380 )>",
    "<NSLayoutConstraint:0x6000021cd950 Onfido.IntroBodyView:0x7fb2de543640.trailing == UIView:0x7fb2de52e380.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021a4f50 UIView:0x7fb2de52e380.width == UIScrollView:0x7fb2d7079e00.width   (active)>",
    "<NSLayoutConstraint:0x6000021f2f30 Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left == UIScrollView:0x7fb2d7079e00.left   (active)>",
    "<NSLayoutConstraint:0x6000021f3d90 H:[UIScrollView:0x7fb2d7079e00]-(0)-|(LTR)   (active, names: '|':Onfido.HeaderBodyStructuredView:0x7fb2de52d990 )>",
    "<NSLayoutConstraint:0x6000021a68a0 UIView:0x7fb2d61a63c0.left == Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left   (active)>",
    "<NSLayoutConstraint:0x6000021a5040 H:[Onfido.HeaderBodyStructuredView:0x7fb2de52d990]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d61a63c0 )>",
    "<NSLayoutConstraint:0x6000022637f0 H:|-(0)-[UIView:0x7fb2d61a63c0]   (active, names: '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x600002263890 UIView:0x7fb2d61a63c0.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active)>",
    "<NSLayoutConstraint:0x60000226f7a0 '_UITemporaryLayoutWidth' Onfido.IntroView:0x7fb2d61a7270.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002216940 UIStackView:0x7fb2de52bee0.trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.086873+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000021dc870 H:|-(16)-[UIStackView:0x7fb2de52e6b0]   (active, names: '|':Onfido.HeaderStructuredContentView:0x7fb2de52e4f0 )>",
    "<NSLayoutConstraint:0x6000021df700 UIStackView:0x7fb2de52e6b0.trailing == Onfido.HeaderStructuredContentView:0x7fb2de52e4f0.trailing - 16   (active)>",
    "<NSLayoutConstraint:0x6000021cc780 H:|-(0)-[Onfido.HeaderStructuredContentView:0x7fb2de52e4f0]   (active, names: '|':UIView:0x7fb2de52e380 )>",
    "<NSLayoutConstraint:0x6000021cd3b0 Onfido.HeaderStructuredContentView:0x7fb2de52e4f0.trailing == UIView:0x7fb2de52e380.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021a4f50 UIView:0x7fb2de52e380.width == UIScrollView:0x7fb2d7079e00.width   (active)>",
    "<NSLayoutConstraint:0x6000021f2f30 Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left == UIScrollView:0x7fb2d7079e00.left   (active)>",
    "<NSLayoutConstraint:0x6000021f3d90 H:[UIScrollView:0x7fb2d7079e00]-(0)-|(LTR)   (active, names: '|':Onfido.HeaderBodyStructuredView:0x7fb2de52d990 )>",
    "<NSLayoutConstraint:0x6000021a68a0 UIView:0x7fb2d61a63c0.left == Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left   (active)>",
    "<NSLayoutConstraint:0x6000021a5040 H:[Onfido.HeaderBodyStructuredView:0x7fb2de52d990]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d61a63c0 )>",
    "<NSLayoutConstraint:0x6000022637f0 H:|-(0)-[UIView:0x7fb2d61a63c0]   (active, names: '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x600002263890 UIView:0x7fb2d61a63c0.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active)>",
    "<NSLayoutConstraint:0x60000226f7a0 '_UITemporaryLayoutWidth' Onfido.IntroView:0x7fb2d61a7270.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000021df700 UIStackView:0x7fb2de52e6b0.trailing == Onfido.HeaderStructuredContentView:0x7fb2de52e4f0.trailing - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.088711+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002260910 Primary Button.trailing == bottom_buttons_view.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261540 H:|-(16)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263840 H:|-(0)-[bottom_buttons_view]   (active, names: bottom_buttons_view:0x7fb2de52f520, '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x6000022639d0 bottom_buttons_view.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x60000226f7a0 '_UITemporaryLayoutWidth' Onfido.IntroView:0x7fb2d61a7270.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002260910 Primary Button.trailing == bottom_buttons_view.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.089442+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002217f70 H:|-(16)-[intro_view_steps_summary_...]   (active, names: intro_view_steps_summary_...:0x7fb2de543850, '|':Onfido.IntroBodyView:0x7fb2de543640 )>",
    "<NSLayoutConstraint:0x600002217cf0 intro_view_steps_summary_....trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active, names: intro_view_steps_summary_...:0x7fb2de543850 )>",
    "<NSLayoutConstraint:0x6000021cd6d0 H:|-(0)-[Onfido.IntroBodyView:0x7fb2de543640]   (active, names: '|':UIView:0x7fb2de52e380 )>",
    "<NSLayoutConstraint:0x6000021cd950 Onfido.IntroBodyView:0x7fb2de543640.trailing == UIView:0x7fb2de52e380.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021a4f50 UIView:0x7fb2de52e380.width == UIScrollView:0x7fb2d7079e00.width   (active)>",
    "<NSLayoutConstraint:0x6000021f2f30 Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left == UIScrollView:0x7fb2d7079e00.left   (active)>",
    "<NSLayoutConstraint:0x6000021f3d90 H:[UIScrollView:0x7fb2d7079e00]-(0)-|(LTR)   (active, names: '|':Onfido.HeaderBodyStructuredView:0x7fb2de52d990 )>",
    "<NSLayoutConstraint:0x6000021a68a0 UIView:0x7fb2d61a63c0.left == Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left   (active)>",
    "<NSLayoutConstraint:0x6000021a5040 H:[Onfido.HeaderBodyStructuredView:0x7fb2de52d990]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d61a63c0 )>",
    "<NSLayoutConstraint:0x6000022637f0 H:|-(0)-[UIView:0x7fb2d61a63c0]   (active, names: '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x600002263890 UIView:0x7fb2d61a63c0.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active)>",
    "<NSLayoutConstraint:0x60000226f7a0 '_UITemporaryLayoutWidth' Onfido.IntroView:0x7fb2d61a7270.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002217cf0 intro_view_steps_summary_....trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active, names: intro_view_steps_summary_...:0x7fb2de543850 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.090610+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000022617c0 Primary Button.height >= 48   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002270730 '_UITemporaryLayoutHeight' Onfido.IntroView:0x7fb2d61a7270.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000022617c0 Primary Button.height >= 48   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.091237+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002260eb0 UILabel:0x7fb2de530640.centerY == Primary Button.centerY   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002260870 V:|-(16)-[UILabel:0x7fb2de530640]   (active, names: Primary Button:0x7fb2de5304a0, '|':Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002270730 '_UITemporaryLayoutHeight' Onfido.IntroView:0x7fb2d61a7270.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002260eb0 UILabel:0x7fb2de530640.centerY == Primary Button.centerY   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.091904+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002260870 V:|-(16)-[UILabel:0x7fb2de530640]   (active, names: Primary Button:0x7fb2de5304a0, '|':Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002260960 UILabel:0x7fb2de530640.bottom == Primary Button.bottom - 16   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002270730 '_UITemporaryLayoutHeight' Onfido.IntroView:0x7fb2d61a7270.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002260960 UILabel:0x7fb2de530640.bottom == Primary Button.bottom - 16   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.092596+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002270730 '_UITemporaryLayoutHeight' Onfido.IntroView:0x7fb2d61a7270.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.106485+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002216940 UIStackView:0x7fb2de52bee0.trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active)>",
    "<NSLayoutConstraint:0x600002217200 H:|-(16)-[UIStackView:0x7fb2de52bee0]   (active, names: '|':Onfido.IntroBodyView:0x7fb2de543640 )>",
    "<NSLayoutConstraint:0x6000021cd6d0 H:|-(0)-[Onfido.IntroBodyView:0x7fb2de543640]   (active, names: '|':UIView:0x7fb2de52e380 )>",
    "<NSLayoutConstraint:0x6000021cd950 Onfido.IntroBodyView:0x7fb2de543640.trailing == UIView:0x7fb2de52e380.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021a4f50 UIView:0x7fb2de52e380.width == UIScrollView:0x7fb2d7079e00.width   (active)>",
    "<NSLayoutConstraint:0x6000021f2f30 Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left == UIScrollView:0x7fb2d7079e00.left   (active)>",
    "<NSLayoutConstraint:0x6000021f3d90 H:[UIScrollView:0x7fb2d7079e00]-(0)-|(LTR)   (active, names: '|':Onfido.HeaderBodyStructuredView:0x7fb2de52d990 )>",
    "<NSLayoutConstraint:0x6000021a68a0 UIView:0x7fb2d61a63c0.left == Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left   (active)>",
    "<NSLayoutConstraint:0x6000021a5040 H:[Onfido.HeaderBodyStructuredView:0x7fb2de52d990]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d61a63c0 )>",
    "<NSLayoutConstraint:0x6000022637f0 H:|-(0)-[UIView:0x7fb2d61a63c0]   (active, names: '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x600002263890 UIView:0x7fb2d61a63c0.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active)>",
    "<NSLayoutConstraint:0x600002267610 UIView:0x7fb2d60e5920.left == Onfido.IntroView:0x7fb2d61a7270.left   (active)>",
    "<NSLayoutConstraint:0x600002260500 H:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288230 'UIView-Encapsulated-Layout-Width' UIView:0x7fb2d60e5920.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002216940 UIStackView:0x7fb2de52bee0.trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.107650+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002217cf0 intro_view_steps_summary_....trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active, names: intro_view_steps_summary_...:0x7fb2de543850 )>",
    "<NSLayoutConstraint:0x600002217f70 H:|-(16)-[intro_view_steps_summary_...]   (active, names: intro_view_steps_summary_...:0x7fb2de543850, '|':Onfido.IntroBodyView:0x7fb2de543640 )>",
    "<NSLayoutConstraint:0x6000021cd6d0 H:|-(0)-[Onfido.IntroBodyView:0x7fb2de543640]   (active, names: '|':UIView:0x7fb2de52e380 )>",
    "<NSLayoutConstraint:0x6000021cd950 Onfido.IntroBodyView:0x7fb2de543640.trailing == UIView:0x7fb2de52e380.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021a4f50 UIView:0x7fb2de52e380.width == UIScrollView:0x7fb2d7079e00.width   (active)>",
    "<NSLayoutConstraint:0x6000021f2f30 Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left == UIScrollView:0x7fb2d7079e00.left   (active)>",
    "<NSLayoutConstraint:0x6000021f3d90 H:[UIScrollView:0x7fb2d7079e00]-(0)-|(LTR)   (active, names: '|':Onfido.HeaderBodyStructuredView:0x7fb2de52d990 )>",
    "<NSLayoutConstraint:0x6000021a68a0 UIView:0x7fb2d61a63c0.left == Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left   (active)>",
    "<NSLayoutConstraint:0x6000021a5040 H:[Onfido.HeaderBodyStructuredView:0x7fb2de52d990]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d61a63c0 )>",
    "<NSLayoutConstraint:0x6000022637f0 H:|-(0)-[UIView:0x7fb2d61a63c0]   (active, names: '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x600002263890 UIView:0x7fb2d61a63c0.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active)>",
    "<NSLayoutConstraint:0x600002267610 UIView:0x7fb2d60e5920.left == Onfido.IntroView:0x7fb2d61a7270.left   (active)>",
    "<NSLayoutConstraint:0x600002260500 H:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288230 'UIView-Encapsulated-Layout-Width' UIView:0x7fb2d60e5920.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002217cf0 intro_view_steps_summary_....trailing == Onfido.IntroBodyView:0x7fb2de543640.trailing - 16   (active, names: intro_view_steps_summary_...:0x7fb2de543850 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.108824+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000021dc870 H:|-(16)-[UIStackView:0x7fb2de52e6b0]   (active, names: '|':Onfido.HeaderStructuredContentView:0x7fb2de52e4f0 )>",
    "<NSLayoutConstraint:0x6000021df700 UIStackView:0x7fb2de52e6b0.trailing == Onfido.HeaderStructuredContentView:0x7fb2de52e4f0.trailing - 16   (active)>",
    "<NSLayoutConstraint:0x6000021cc780 H:|-(0)-[Onfido.HeaderStructuredContentView:0x7fb2de52e4f0]   (active, names: '|':UIView:0x7fb2de52e380 )>",
    "<NSLayoutConstraint:0x6000021cd3b0 Onfido.HeaderStructuredContentView:0x7fb2de52e4f0.trailing == UIView:0x7fb2de52e380.trailing   (active)>",
    "<NSLayoutConstraint:0x6000021a4f50 UIView:0x7fb2de52e380.width == UIScrollView:0x7fb2d7079e00.width   (active)>",
    "<NSLayoutConstraint:0x6000021f2f30 Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left == UIScrollView:0x7fb2d7079e00.left   (active)>",
    "<NSLayoutConstraint:0x6000021f3d90 H:[UIScrollView:0x7fb2d7079e00]-(0)-|(LTR)   (active, names: '|':Onfido.HeaderBodyStructuredView:0x7fb2de52d990 )>",
    "<NSLayoutConstraint:0x6000021a68a0 UIView:0x7fb2d61a63c0.left == Onfido.HeaderBodyStructuredView:0x7fb2de52d990.left   (active)>",
    "<NSLayoutConstraint:0x6000021a5040 H:[Onfido.HeaderBodyStructuredView:0x7fb2de52d990]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d61a63c0 )>",
    "<NSLayoutConstraint:0x6000022637f0 H:|-(0)-[UIView:0x7fb2d61a63c0]   (active, names: '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x600002263890 UIView:0x7fb2d61a63c0.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active)>",
    "<NSLayoutConstraint:0x600002267610 UIView:0x7fb2d60e5920.left == Onfido.IntroView:0x7fb2d61a7270.left   (active)>",
    "<NSLayoutConstraint:0x600002260500 H:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288230 'UIView-Encapsulated-Layout-Width' UIView:0x7fb2d60e5920.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000021df700 UIStackView:0x7fb2de52e6b0.trailing == Onfido.HeaderStructuredContentView:0x7fb2de52e4f0.trailing - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.110485+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002260910 Primary Button.trailing == bottom_buttons_view.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002261540 H:|-(16)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263840 H:|-(0)-[bottom_buttons_view]   (active, names: bottom_buttons_view:0x7fb2de52f520, '|':Onfido.IntroView:0x7fb2d61a7270 )>",
    "<NSLayoutConstraint:0x6000022639d0 bottom_buttons_view.trailing == Onfido.IntroView:0x7fb2d61a7270.trailing   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002267610 UIView:0x7fb2d60e5920.left == Onfido.IntroView:0x7fb2d61a7270.left   (active)>",
    "<NSLayoutConstraint:0x600002260500 H:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|(LTR)   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288230 'UIView-Encapsulated-Layout-Width' UIView:0x7fb2d60e5920.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002260910 Primary Button.trailing == bottom_buttons_view.trailing - 16   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.111343+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002260960 UILabel:0x7fb2de530640.bottom == Primary Button.bottom - 16   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x6000022623a0 V:[UIStackView:0x7fb2de52fed0]-(0)-|   (active, names: '|':Onfido.OnfidoLogoView:0x7fb2de52f750 )>",
    "<NSLayoutConstraint:0x600002260870 V:|-(16)-[UILabel:0x7fb2de530640]   (active, names: Primary Button:0x7fb2de5304a0, '|':Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002263430 Onfido.OnfidoLogoView:0x7fb2de52f750.top == UIStackView:0x7fb2de52fed0.top   (active)>",
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263700 UIView:0x7fb2d60e5920.top == Onfido.IntroView:0x7fb2d61a7270.top   (active)>",
    "<NSLayoutConstraint:0x600002263930 V:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288280 'UIView-Encapsulated-Layout-Height' UIView:0x7fb2d60e5920.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002260960 UILabel:0x7fb2de530640.bottom == Primary Button.bottom - 16   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.112450+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000022623a0 V:[UIStackView:0x7fb2de52fed0]-(0)-|   (active, names: '|':Onfido.OnfidoLogoView:0x7fb2de52f750 )>",
    "<NSLayoutConstraint:0x600002263430 Onfido.OnfidoLogoView:0x7fb2de52f750.top == UIStackView:0x7fb2de52fed0.top   (active)>",
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263700 UIView:0x7fb2d60e5920.top == Onfido.IntroView:0x7fb2d61a7270.top   (active)>",
    "<NSLayoutConstraint:0x600002263930 V:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288280 'UIView-Encapsulated-Layout-Height' UIView:0x7fb2d60e5920.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002263430 Onfido.OnfidoLogoView:0x7fb2de52f750.top == UIStackView:0x7fb2de52fed0.top   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-11-09 13:31:59.113209+0100  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>",
    "<NSLayoutConstraint:0x600002261590 V:|-(8)-[Primary Button]   (active, names: Primary Button:0x7fb2de5304a0, bottom_buttons_view:0x7fb2de52f520, '|':bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x6000022618b0 Onfido.OnfidoLogoView:0x7fb2de52f750.bottom == bottom_buttons_view.bottom - 40   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263c00 bottom_buttons_view.height <= 0.4*Onfido.IntroView:0x7fb2d61a7270.height   (active, names: bottom_buttons_view:0x7fb2de52f520 )>",
    "<NSLayoutConstraint:0x600002263700 UIView:0x7fb2d60e5920.top == Onfido.IntroView:0x7fb2d61a7270.top   (active)>",
    "<NSLayoutConstraint:0x600002263930 V:[Onfido.IntroView:0x7fb2d61a7270]-(0)-|   (active, names: '|':UIView:0x7fb2d60e5920 )>",
    "<NSLayoutConstraint:0x600002288280 'UIView-Encapsulated-Layout-Height' UIView:0x7fb2d60e5920.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002261770 V:[Primary Button]-(8)-[Onfido.OnfidoLogoView:0x7fb2de52f750]   (active, names: Primary Button:0x7fb2de5304a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by buh** [comment]
Hey guys at Onfido, is there any particular reason why you dropped support for iOS 11/12 in version 23?

**Comment by buh** [comment]
With the new special version of the SDK we now see a slightly different crash for the same iPhone XR/11, which hopefully will now be easier to fix:
```swift
Fatal Exception: NSInvalidArgumentException
*** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x12586c __exceptionPreprocess
1  libobjc.A.dylib                0x6c50 objc_exception_throw
2  AVFCapture                     0x8ce48 -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:]
3  Onfido                         0x773ac _hidden#10401_ (__hidden#2949_)
4  Onfido                         0x1813e0 PhotoCaptureView.didTapCaptureButton() + 334 (__hidden#26142_:334)
5  Onfido                         0x17b644 _hidden#25907_ (__hidden#2949_)
6  UIKitCore                      0xbcfe78 -[UIApplication sendAction:to:from:forEvent:]
7  UIKitCore                      0x506ef0 -[UIControl sendAction:to:forEvent:]
8  UIKitCore                      0x507244 -[UIControl _sendActionsForEvents:withEvent:]
9  UIKitCore                      0x505aa8 -[UIControl touchesEnded:withEvent:]
10 UIKitCore                      0xc0e4e4 -[UIWindow _sendTouchesForEvent:]
11 UIKitCore                      0xc0fe4c -[UIWindow sendEvent:]
12 UIKitCore                      0xbe91d4 -[UIApplication sendEvent:]
13 UIKitCore                      0xc730ec __dispatchPreprocessedEventFromEventQueue
14 UIKitCore                      0xc760a4 __processEventQueue
15 UIKitCore                      0xc6d550 __eventFetcherSourceCallback
16 CoreFoundation                 0xa176c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
17 CoreFoundation                 0xa1668 __CFRunLoopDoSource0
18 CoreFoundation                 0xa0960 __CFRunLoopDoSources0
19 CoreFoundation                 0x9aa8c __CFRunLoopRun
20 CoreFoundation                 0x9a21c CFRunLoopRunSpecific
21 GraphicsServices               0x3784 GSEventRunModal
22 UIKitCore                      0xbc8ee8 -[UIApplication _run]
23 UIKitCore                      0xbce75c UIApplicationMain
```
